# server
server:
    port: 8085
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

# jdbc
spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:xe
        username: reelreview
        password: 1234

    # jpa
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.Oracle10gDialect
                format_sql: true

logging:
    level:
        # hibernate가 남기는 모든 로그를 debug모드로 설정
        # jpa hibernate가 생성하는 sql이 로거를 통해서 출력되도록 하는 설정
        org.hibernate.SQL: debug
        org.hibernate.type: trace # 실제 들어가는 파라미터값을 출력해주는 설정